#!/bin/bash

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=$1
need_config "$CONFIG"
source_config

/sbin/ip link set dev "$DEVICE" down
/sbin/ip link del "$DEVICE"

exec /etc/sysconfig/network-scripts/ifdown-eth "$CONFIG"
exec /etc/sysconfig/network-scripts/ifdown-post "$CONFIG"
